/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2017-07-24 12:45:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("function loadDoc() {\t\r\n");
      out.write("\t  var xhttp = new XMLHttpRequest();\r\n");
      out.write("\t  xhttp.onreadystatechange = function() {\r\n");
      out.write("\t    if (this.readyState == 4 && this.status == 200) {\t    \r\n");
      out.write("\t    var data=JSON.parse(this.responseText);\r\n");
      out.write("\t      document.getElementById(\"empId\").value =data.empId;\r\n");
      out.write("\t      document.getElementById(\"empName\").value =data.empName;\r\n");
      out.write("\t      document.getElementById(\"contactNo\").value =data.contactNo;\r\n");
      out.write("\t     document.getElementById(\"department\").value =data.department;\r\n");
      out.write("\t     document.getElementById(\"family\").value =data.family;\r\n");
      out.write("\t    }\r\n");
      out.write("\t  };\r\n");
      out.write("\t  //xhttp.open(\"GET\", \"ajax_info.txt\", true);\r\n");
      out.write("\t  xhttp.open(\"GET\", \"helloworld\", true);\r\n");
      out.write("\t  xhttp.send();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<STYLE>\r\n");
      out.write("#empDetails  tr{\r\n");
      out.write("height:50px;\r\n");
      out.write("}\r\n");
      out.write("</STYLE>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"empDetailsForm\" action=\"helloworld\" method=\"GET\">\r\n");
      out.write(" <table align=\"center\" id=\"empDetails\">\r\n");
      out.write(" <tr>\r\n");
      out.write("         <td colspan=\"2\"><h3>IDeaS Annual Picnic Form<h3></h3></td>         \r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("         <td>Employee ID</td>\r\n");
      out.write("         <td><input type=\"text\" id=\"empId\" value=\"\"> <input type=\"button\" value=\"fetch\" onclick=\"loadDoc()\"/></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("         <td>Employee Name</td>\r\n");
      out.write("         <td><input type=\"text\" id=\"empName\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("         <td>Contact Number</td>\r\n");
      out.write("         <td><input type=\"text\" id=\"contactNo\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     \t<tr>\r\n");
      out.write("         <td>Department</td>\r\n");
      out.write("         <td><select id=\"department\">\r\n");
      out.write("             <option value=\"0\" >Select Department</option>\r\n");
      out.write("             <option value=\"SD\" >SD</option>\r\n");
      out.write("             <option value=\"QA\" >QA</option>\r\n");
      out.write("             <option value=\"CARE\" >CARE</option>\r\n");
      out.write("             <option value=\"ROA\" >ROA</option>\r\n");
      out.write("             <option value=\"TECHOPS\" >TECHOPS</option>\r\n");
      out.write("            </select>\r\n");
      out.write("           </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     \t<tr>\r\n");
      out.write("         <td>Set Of Family</td>\r\n");
      out.write("         <td><select id=\"family\">\r\n");
      out.write("             <option value=\"0\" >Select Family</option>\r\n");
      out.write("             <option value=\"OnlyMe\" >Only Me</option>\r\n");
      out.write("             <option value=\"Self+Spouse\" >Self+Spouse</option>\r\n");
      out.write("             <option value=\"Self+Spouse+Kids\" >Self+Spouse+Kids</option>\r\n");
      out.write("             <option value=\"Self+Parents\" >Self+Parents</option>             \r\n");
      out.write("            </select>\r\n");
      out.write("           </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>         \r\n");
      out.write("         <td colspan=\"2\"><input type=\"submit\" id=\"confirm\" value=\"Confirm\"></td>\r\n");
      out.write("     </tr>       \r\n");
      out.write(" </table>\r\n");
      out.write(" </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
